#include "CppGenerator.h"

#include <sstream>
#include <stdexcept>
#include <unordered_map>

namespace quantc {

std::string CppGenerator::generate(const Program& program) const {
    std::ostringstream out;
    out << "// Generated by QuantC. Do not edit manually.\n";
    out << "#include <cmath>\n";
    out << "#include <cstdint>\n";
    out << "#include <iostream>\n";
    out << "#include <string>\n\n";

    for (const auto& declaration : program.classes) {
        out << generateClass(declaration) << "\n";
    }

    out << "int main() {\n";
    for (const auto& statement : program.statements) {
        out << generateStatement(statement, 1);
    }
    out << "    return 0;\n";
    out << "}\n";
    return out.str();
}

std::string CppGenerator::generateClass(const ClassDecl& declaration) const {
    std::ostringstream out;
    out << "class " << declaration.name << " {\n";
    for (const auto& field : declaration.fields) {
        switch (field.modifiers.visibility) {
            case Visibility::Public: out << "public:\n"; break;
            case Visibility::Private: out << "private:\n"; break;
            case Visibility::Default: out << "private:\n"; break;
            default: out << "private:\n"; break;
        }
        out << generateField(field);
    }
    out << "};\n";
    return out.str();
}

std::string CppGenerator::generateField(const VariableDecl& declaration) const {
    std::ostringstream out;
    out << "    ";
    if (declaration.modifiers.storage == Storage::Global) out << "inline static ";
    if (declaration.modifiers.mutability == Mutability::Constexpr) out << "constexpr ";
    else if (declaration.modifiers.mutability == Mutability::Const) out << "const ";
    out << generateType(declaration.type) << ' ' << declaration.name;
    if (declaration.initializer) out << " = " << generateExpression(*declaration.initializer);
    out << ";\n";
    return out.str();
}

std::string CppGenerator::generateStatement(const Statement& statement, int indentLevel) const {
    std::ostringstream out;
    out << indent(indentLevel);
    if (statement.kind == Statement::Kind::Variable) {
        const auto& variable = statement.variable;
        if (variable.modifiers.storage == Storage::Global) out << "static ";
        if (variable.modifiers.mutability == Mutability::Constexpr) out << "constexpr ";
        else if (variable.modifiers.mutability == Mutability::Const) out << "const ";
        out << (variable.inferred ? "auto" : generateType(variable.type)) << ' ' << variable.name;
        if (variable.initializer) out << " = " << generateExpression(*variable.initializer);
        out << ";\n";
        return out.str();
    }

    if (!statement.expression) return {};
    if (statement.expression->kind == Expr::Kind::Call && !statement.expression->children.empty()) {
        const auto& callee = *statement.expression->children.front();
        if (callee.kind == Expr::Kind::Identifier && callee.value == "print") {
            if (statement.expression->children.size() == 1) {
                out << "std::cout << '\\n';\n";
            } else {
                out << "std::cout << " << generateExpression(*statement.expression->children[1]);
                for (std::size_t i = 2; i < statement.expression->children.size(); ++i) {
                    out << " << ' ' << " << generateExpression(*statement.expression->children[i]);
                }
                out << " << '\\n';\n";
            }
            return out.str();
        }
    }

    out << generateExpression(*statement.expression) << ";\n";
    return out.str();
}

std::string CppGenerator::generateExpression(const Expr& expression) const {
    switch (expression.kind) {
        case Expr::Kind::Identifier:
        case Expr::Kind::Number:
        case Expr::Kind::String:
        case Expr::Kind::Character:
        case Expr::Kind::Boolean:
            return expression.value;
        case Expr::Kind::Null:
            return "nullptr";
        case Expr::Kind::New: {
            std::ostringstream out;
            out << generateType(expression.type) << '{';
            for (std::size_t i = 0; i < expression.children.size(); ++i) {
                if (i != 0) out << ", ";
                out << generateExpression(*expression.children[i]);
            }
            out << '}';
            return out.str();
        }
        case Expr::Kind::MemberAccess:
            return generateExpression(*expression.children.at(0)) + "." + expression.value;
        case Expr::Kind::Call: {
            std::ostringstream out;
            out << generateExpression(*expression.children.at(0)) << '(';
            for (std::size_t i = 1; i < expression.children.size(); ++i) {
                if (i != 1) out << ", ";
                out << generateExpression(*expression.children[i]);
            }
            out << ')';
            return out.str();
        }
        case Expr::Kind::Binary: {
            const auto op = expression.value == "and" ? "&&" : expression.value == "or" ? "||" : expression.value;
            if (op == "**") {
                return "std::pow(" + generateExpression(*expression.children.at(0)) + ", " +
                       generateExpression(*expression.children.at(1)) + ")";
            }
            return "(" + generateExpression(*expression.children.at(0)) + " " + op + " " +
                   generateExpression(*expression.children.at(1)) + ")";
        }
        case Expr::Kind::Unary: {
            const auto op = expression.value == "not" ? "!" : expression.value;
            return op + generateExpression(*expression.children.at(0));
        }
        default:
            throw std::runtime_error("Unsupported expression kind");
    }
}

std::string CppGenerator::generateType(const TypeRef& type) const {
    static const std::unordered_map<std::string, std::string> builtinTypes = {
        {"byte", "std::int8_t"}, {"short", "std::int16_t"}, {"int", "std::int32_t"},
        {"long", "std::int64_t"}, {"ubyte", "std::uint8_t"}, {"ushort", "std::uint16_t"},
        {"uint", "std::uint32_t"}, {"ulong", "std::uint64_t"}, {"float", "float"},
        {"double", "double"}, {"char", "char"}, {"string", "std::string"},
        {"boolean", "bool"}, {"void", "void"}
    };

    const auto it = builtinTypes.find(type.name);
    std::ostringstream out;
    out << (it == builtinTypes.end() ? type.name : it->second);
    if (!type.genericArgs.empty()) {
        out << '<';
        for (std::size_t i = 0; i < type.genericArgs.size(); ++i) {
            if (i != 0) out << ", ";
            out << generateType(type.genericArgs[i]);
        }
        out << '>';
    }
    return out.str();
}

std::string CppGenerator::indent(int level) const {
    return std::string(static_cast<std::size_t>(level) * 4, ' ');
}

} // namespace quantc
